image_file: "/home/collar/data/1.png"
pcd_file: "/home/collar/data/1.pcd"

camera:
    camera_inner: [1196, 0.0,      717,
                0.0,     1196,  581,
                0.0,     0.0,      1.0     ]
    camera_distortion: [0,  0, 0 , 0, 0]

calib:
    depth_weight: 0.7
    init_transform: [1.57 , -1.57 , 0 , 0 , 0 , 0]
    max_orig_lines_num: 250
    max_proj_lines_num: 250

