frame_num: 1

image_file0: "/home/collar/hdd1/data/17.png"
pcd_file0: "/home/collar/hdd1/data/17.pcd"

image_file1: "/home/collar/data/vanishing_data/30.png"
pcd_file1: "/home/collar/data/vanishing_data/30.pcd"

image_file2: "/home/collar/data/vanishing_data/43.png"
pcd_file2: "/home/collar/data/vanishing_data/43.pcd"

image_file3: "/home/collar/data/vanishing_data/43.png"
pcd_file3: "/home/collar/data/vanishing_data/43.pcd"

image_file4: "/home/collar/data/vanishing_data/19.png"
pcd_file4: "/home/collar/data/vanishing_data/19.pcd"

camera:
    camera_inner: [1196.4418565730384, 0.0,      717.7188725924585,
                0.0,     1196.3710009482545,  581.0874277311857,
                0.0,     0.0,      1.0]
    # camera_distortion: [-0, -0, -0, 0, 0.0]
    camera_distortion: [-0.09416244866122019, 0.08403929739634683, -0.00018055391689027767, -3.122884805295416e-05, 0.0]



calib:
    # depth_weight: 0
    depth_weight: 0.1
    ExtrinsicMat: [0, -1 , -0 , 0 ,
                   -0, 0, -1 , 0 ,
                   1, 0, -0 ,0,
                   0.0 , 0.0 , 0.0 , 1.0]

    max_orig_lines_num: 300
    max_proj_lines_num: 300
    line_length: 230

